name: Scheduled Task

on:
  schedule:
    - cron: '*/10 * * * *'  # 每十分钟触发一次任务

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Run curl command
        run: curl ${{ secrets.CronUrl }}
